name: Brewery
version: 3.0
main: com.dre.brewery.P
softdepend: [LWC, LogBlock, WorldGuard, GriefPrevention, Vault, ChestShop, Shopkeepers, Towny, BlockLocker]
authors: [Milan Albrecht, Frank Baumann, ProgrammerDan, Daniel Saukel]
api-version: 1.13
commands:
  brewery:
    description: Mostly admin commands to create/modify Brews and drunkeness
    aliases: [brew]
permissions:
# -- Groups --
# User
  brewery.user:
    description: Access to everything needed for brewing
    default: true
    children:
      brewery.cmd.unlabel: true
      brewery.createbarrel: true
      brewery.openbarrel: true
      brewery.cauldron.time: true
      brewery.cauldron.insert: true
      brewery.cauldron.fill: true
# Mod
  brewery.mod:
    description: Allow to maintain Wakeup Points and to login even if overdrunken
    children:
      brewery.user: true
      brewery.cmd.wakeup: true
      brewery.bypass.logindeny: true
# Admin
  brewery.admin:
    description: Gives access to Every Command and most bypasses
    default: op
    children:
      brewery.user: true
      brewery.mod: true
      brewery.cmd.info: true
      brewery.cmd.infoOther: true
      brewery.cmd.seal: true
      brewery.cmd.puke: true
      brewery.cmd.pukeOther: true
      brewery.cmd.player: true
      brewery.cmd.create: true
      brewery.cmd.drink: true
      brewery.cmd.drinkOther: true
      brewery.cmd.copy: true
      brewery.cmd.delete: true
      brewery.cmd.static: true
      brewery.cmd.reload: true
# *
  brewery.*:
    description: Gives Access to every Permission, including bypasses and overrides
    children:
      brewery.user: true
      brewery.mod: true
      brewery.admin: true
      brewery.bypass.overdrink: true
      brewery.bypass.teleport: true

# -- Commands --
  brewery.cmd.unlabel:
    description: Remove Parts of the Potionlabel
  brewery.cmd.info:
    description: Information about your own drunkeness
  brewery.cmd.infoOther:
    description: Information about the drunkeness of another Player
  brewery.cmd.seal:
    description: Open the Brew Sealer by command
  brewery.cmd.puke:
    description: Make yourself puke
  brewery.cmd.pukeOther:
    description: Make other Players puke
  brewery.cmd.player:
    description: Set Player-values
  brewery.cmd.wakeup:
    description: Set, Check and Remove Wakeup Points
  brewery.cmd.create:
    description: Create Brews
  brewery.cmd.drink:
    description: Simulate drinking Brews
  brewery.cmd.drinkOther:
    description: Simulate other players drinking Brews
  brewery.cmd.copy:
    description: Copy Brews
  brewery.cmd.delete:
    description: Delete Brews
  brewery.cmd.static:
    description: Make Brews Static
  brewery.cmd.reload:
    description: Reload config

# -- Barrel --
  brewery.createbarrel:
    description: Allow to create all types of Barrels
    children:
      brewery.createbarrel.small: true
      brewery.createbarrel.big: true
  brewery.createbarrel.small:
    description: Allow to create small Barrels
  brewery.createbarrel.big:
    description: Allow to create big Barrels

  brewery.openbarrel:
    description: Allow to open all types of Barrels
    children:
      brewery.openbarrel.small: true
      brewery.openbarrel.big: true
      brewery.openbarrel.mc: true
  brewery.openbarrel.small:
    description: Allow to open small Barrels
  brewery.openbarrel.big:
    description: Allow to open big Barrels
  brewery.openbarrel.mc:
    description: Allow to open Minecraft Barrels

# -- Cauldron --
  brewery.cauldron.time:
    description: View the current Cooking time of a cauldron with a watch
  brewery.cauldron.insert:
    description: Add Ingredients to the Cauldron
  brewery.cauldron.fill:
    description: Fill a Bottle from a Cauldron with a brewery brew

# -- Bypasses --
  brewery.bypass.logindeny:
    description: Can always login, even with extreme drunkeness
  brewery.bypass.overdrink:
    description: Will despite config-setting not be kicked on overdrink
  brewery.bypass.teleport:
    description: Will despite config-setting not be teleported on login
